print("hello \"world\" world")
print('I\'m deepak')
print("line A\n line B \n line C")
print("name\tDeepak")
print("this is backslash\\")
print("this is double backslash\\\\")
print("hell\blo")
